name: DynamicArrayTest

on: [push]

env:
  BUILD_TYPE: Release
  TARGET_NAME: DynamicArray
  PATH: ${{github.workspace}}/structs/DynamicArray

jobs:
  build:
    runs-on: windows-2019
    steps:

    - name: V3
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Configure CMake
      run: cmake -G "Visual Studio 16 2019" -H "${{env.PATH}}" -B "${{env.PATH}}/build"
    
    - name: Build
      run: cmake --build "${{env.PATH}}/build" --config ${{env.BUILD_TYPE}} --target ${{env.TARGET_NAME}}

    - name: Run test
      run: "${{env.PATH}}/build/${{env.BUILD_TYPE}}/test.exe"

    - name: Check errorlevel
      run: echo Exit Code is %errorlevel%
